### ISSUE TITLE
Horizontal overflow scrollbars

### ISSUE THREAD

**Issue by charliegeiger89** [gilbox/react-spark-scroll#1]
Using Chrome 41

I am seeing horizontal overflow bars appear for certain text components. You should add in overflow styling to prevent it.

```
overflow-x: hidden;
```

**Comment by gilbox** [comment]
hmm thanks. All text is `display: block` at 100% width automatically so doesn't really make sense. I can't reproduce in Chrome 41. Can you tell me which text in particular?

**Comment by gilbox** [comment]
ah ok i realized that the viewport's scrollbar shows up sometimes. I added `overflow-x: hidden;` to the `body`. Hopefully that's what you meant.

**Comment by charliegeiger89** [comment]
That was it. It appears to be fixed now.

**Comment by gilbox** [comment]
thanks!
