### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by ayozebarrera** [gilbox/react-spark-scroll#14]
Hi, I'm trying to use the package

I'm importing using (ES2015) :

``` js
import { SparkScroll, SparkProxy } from 'react-spark-scroll-gsap';
```

but when I add for example this to the render:

``` jsx
<SparkScroll.h1
  timeline={{
    topBottom: {opacity: 0},
    centerCenter: {opacity: 1}
  }}>
  fade
</SparkScroll.h1>
```

I always get "can't read h1 of undefined". Why? I guess I'm importing it wrong

**Comment by ayozebarrera** [comment]
Nvm, I'm using react-track :+1:

**Comment by zlwaterfield** [comment]
@ayozebarrera I am getting the same error, how did you fix it?
