### ISSUE TITLE
setState warnings when transitioning between pages / components - window.eventListeners not clearing

### ISSUE THREAD

**Issue by tim-field** [gilbox/react-spark-scroll#15]
I'm using this library in a react router project, whenever we jump to a new page we get numerous setState warnings 

> Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.

It seems window.scroll and resize eventListeners aren't getting removed after the component is unmounted.? Any clues on what can be done to prevent it ?

```
return (
  <SparkScroll.li
    className={cssClasses}
    timeline={{
      'bottomBottom+80': {
        onDown: () => this.setState({inView:true}),
        onUp:   () => this.setState({inView:false})
      }
    }}
    >
    <div>
      ...
    </div>
  </SparkScroll.li>
)
```

Thanks

**Comment by gilbox** [comment]
I think you're right, `lib/index.js` needs a `componentWillUnmount` method. `sparkFactory` could return a function to handle removing the event listeners and that function can be called from `componentWillUnmount`. Interested in putting a PR for that?

**Comment by tim-field** [comment]
Hmm my patch seems to cause all sorts of problems if you have nested spark scroll items. Not sure how to resolve this.

**Comment by gilbox** [comment]
what do you mean by _nested spark scroll items_ ?

**Comment by tim-field** [comment]
As in nested JSX elements.  Pages without nested SparkScoll elements seem to work fine, and clean up events correctly. A page with nested SparkScroll elements will not again work after its been cleaned up. i.e. if you come back to the page it won't show the SparkScroll content at all. 

```
 <SparkScroll.div>
   <SparkScroll.div
timeline={{
              topTop: {
                onDown: () => this.setState({articleInView:true}),
                onUp:   () => this.setState({articleInView:false})
              }
            }}
> ...
</SparkScroll.div>
</SparkScroll.div>
```

**Comment by gilbox** [comment]
hmm do you get any errors in the console?

**Comment by tim-field** [comment]
Unfortunately I don't.

On Fri, Feb 19, 2016 at 10:46 AM, Gil Birman notifications@github.com
wrote:

> hmm do you get any errors in the console?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gilbox/react-spark-scroll/issues/15#issuecomment-185935940
> .

## 

Tim Field - The Fold
0226855011

**Comment by joaogranado** [comment]
@tim-field @gilbox it looks like that when the `cleanup` event is emitted by spark's `EventEmitter` instance, every subscribed element will inadvertently remove `window`'s event listeners. It looks like this event strategy was used since `onScroll` accesses variables inside the parent `spark` scope, and moving `onScroll` outside of `spark` scope would need a little more effort. I would suggest to remove the `EventListener` dependency and create `cleanup` and `invalidate` inside `spark` such as:

``` js
const spark = function(element, proxyElementFn, timeline, options) {
  // ...

  window.addEventListener('scroll', onScroll, false);
  window.addEventListener('resize', onInvalidate, false);

  spark.cleanup = () => {
    window.removeEventListener('scroll', onScroll);
    window.removeEventListener('resize', onInvalidate);
  };

  spark.invalidate = onInvalidate;
}
```

**Comment by gilbox** [comment]
thanks @joaogranado ! could you make a PR for this?

**Comment by joaogranado** [comment]
@gilbox sure.
