### ISSUE TITLE
Warning: Unknown prop `timeline` on <div> tag

### ISSUE THREAD

**Issue by buesing** [gilbox/react-spark-scroll#23]
Everything is working great but I'm getting this error in the console:

`Warning: Unknown prop `timeline` on <div> tag. Remove this prop from the element.`

I'm guessing this is maybe because the library is trying to pass on the timeline prop to the actual div being rendered?

**Comment by Jascha-Sundaresan** [comment]
I fixed this in the PR that just got merged in.

This should be closed.

**Comment by gilbox** [comment]
thanks!
