### ISSUE TITLE
[Feature Request]Make formulas config support negative number

### ISSUE THREAD

**Issue by NE-SmallTown** [gilbox/react-spark-scroll#29]
Now we can set something like 'topTop+100',but can't set it to 'topTop-100',of course we can config by [`_sparkFormulas`](https://github.com/gilbox/react-spark-scroll#formulas),but that's  unnecessary and we should keep the config symmetrical

**Comment by gilbox** [comment]
That's strange, I would have thought negative number would work. Can you describe what happens when you try it?

**Comment by NE-SmallTown** [comment]
Sorry,I have not try to use negative number,the reason of file this issue is that I just see positive number in the doc,so it lets me think that we can't use negative number

**Comment by NE-SmallTown** [comment]
-<title>This test checks that RTCConfiguration.iceCandidatePoolSize is set</title>
 +<meta charset="utf-8">

**Comment by NE-SmallTown** [comment]
```diff
public class Hello1
{
   public static void Main()
   {
-      System.Console.WriteLine("Hello, World!");
+      System.Console.WriteLine("Rock all night long!");
   }
}
```

**Comment by NE-SmallTown** [comment]
Close because we can set it to negative number.Hope that we could add this to the doc :smiley:
